name: Flutter CI

on:
  push:
    branches: [ main ] # Trigger workflow on push to main branch
  pull_request:
    branches: [ main ] # Trigger workflow on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use Ubuntu as the runner environment
    steps:
      - uses: actions/checkout@v3 # Step 1: Checkout the code from the repository
      - uses: subosito/flutter-action@v2 # Step 2: Set up Flutter environment
        with:
          channel: stable # Use the stable channel of Flutter
      - run: flutter pub get # Step 3: Install project dependencies
      - run: flutter test # Step 4: Run tests to ensure code quality
      - run: flutter build apk # Step 5: Build the APK for Android
      - name: Upload APK # Step 6: Upload the APK as an artifact for download
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/flutter-apk/app-release.apk